import type { CascadeGraph, CascadeChild } from '../cascade-graph.js';

/**
 * Generates TypeScript code for the cascade graph constant
 */
export function emitCascadeGraph(graph: CascadeGraph): string {
  const lines: string[] = [];

  lines.push('/* eslint-disable */');
  lines.push('// @ts-nocheck');
  lines.push('// Auto-generated by prisma-soft-cascade');
  lines.push('// Do not edit this file manually');
  lines.push('');
  lines.push('/** Cascade child configuration */');
  lines.push('export interface CascadeChild {');
  lines.push('  model: string;');
  lines.push('  foreignKey: string[];');
  lines.push('  parentKey: string[];');
  lines.push('  isSoftDeletable: boolean;');
  lines.push('  deletedAtField: string | null;');
  lines.push('}');
  lines.push('');
  lines.push('/** Maps parent model names to their cascade children */');
  lines.push('export type CascadeGraph = Record<string, CascadeChild[]>;');
  lines.push('');
  lines.push('/** The cascade graph for this schema */');
  lines.push('export const CASCADE_GRAPH: CascadeGraph = {');

  const entries = Object.entries(graph);
  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    if (entry === undefined) continue;
    const [modelName, children] = entry;

    const isLast = i === entries.length - 1;
    lines.push(`  ${JSON.stringify(modelName)}: ${formatChildrenArray(children)}${isLast ? '' : ','}`);
  }

  lines.push('};');
  lines.push('');

  // Export model list for convenience
  lines.push('/** List of all model names */');
  lines.push(`export const MODEL_NAMES = ${JSON.stringify(Object.keys(graph))} as const;`);
  lines.push('');
  lines.push('/** Type for model names */');
  lines.push('export type ModelName = typeof MODEL_NAMES[number];');

  return lines.join('\n');
}

function formatChildrenArray(children: CascadeChild[]): string {
  if (children.length === 0) {
    return '[]';
  }

  const formatted = children.map((child) => {
    return JSON.stringify(child);
  });

  if (formatted.join(', ').length < 80) {
    return `[${formatted.join(', ')}]`;
  }

  return `[\n    ${formatted.join(',\n    ')}\n  ]`;
}
