import type { ParsedSchema } from '../dmmf-parser.js';

/**
 * Generates the main index.ts export file
 */
export function emitIndex(schema: ParsedSchema): string {
  const lines: string[] = [];

  lines.push('/* eslint-disable */');
  lines.push('// @ts-nocheck');
  lines.push('// Auto-generated by prisma-safe-delete');
  lines.push('// Do not edit this file manually');
  lines.push('');
  lines.push('// Re-export types');
  const hasAuditableModels = schema.models.some((m) => m.isAuditable);
  const typeExports = ['SafePrismaClient', 'IncludingDeletedClient', 'OnlyDeletedClient', 'CascadeResult'];
  if (hasAuditableModels) {
    typeExports.push('WrapOptions', 'AuditContext');
  }
  lines.push(`export type { ${typeExports.join(', ')} } from './types.js';`);

  // Export individual delegate types
  for (const model of schema.models) {
    lines.push(`export type { Safe${model.name}Delegate } from './types.js';`);
  }

  lines.push('');
  lines.push('// Re-export cascade graph');
  lines.push("export { CASCADE_GRAPH, MODEL_NAMES } from './cascade-graph.js';");
  lines.push("export type { CascadeGraph, CascadeChild, ModelName } from './cascade-graph.js';");
  lines.push('');
  lines.push('// Re-export wrapper function');
  lines.push("export { wrapPrismaClient } from './runtime.js';");
  lines.push('');
  lines.push('// Re-export filter helpers');
  lines.push("export { onlyDeleted, excludeDeleted, includingDeleted } from './runtime.js';");

  return lines.join('\n');
}
